version: 0.2

env:
  variables:
    S3_BUCKET_NAME: "bayersdorfer-website-s3-bucket"

phases:
  install:
    commands:
      - echo In install
      - gem install jekyll jekyll-paginate jekyll-sitemap jekyll-gist github-pages
  build:
    commands:
      - echo In build.
      - bundle exec jekyll build
  post_build:
    commands:
      - echo In post build phase
      - aws s3 sync _site/ s3://bayersdorfercom
